# *Setup*

In [1]:
%load_ext autoreload
%autoreload 2

In [58]:
%%time
import numpy as np
import pandas as pd

from hid_avan.Thiessen import thiessen

CPU times: total: 0 ns
Wall time: 0 ns

In [40]:
def head_tail_info(df:pd.DataFrame, n:int=5):
    display(pd.concat((df.head(n), df.tail(n))), df.info())

def extract_daily_pr_array_from_funceme_dataset(funceme_txt_path, date_start, date_end, missing_pr=-999.):
    complete_array = np.loadtxt(funceme_txt_path)
    pr_array = complete_array[:, 3:]
    pr_array_w_missing = np.where(pr_array == missing_pr, np.nan, pr_array)

    date_column = np.reshape(pd.date_range(start=date_start, end=date_end, freq='D'), (-1, 1))
    
    pr_array

#def load_funceme_precipitation(missing_pr=-999.

In [ ]:
{'id':2173,
 'coord':[-40.4797, -5.4164],
 'pr_daily':[]}

In [60]:
pd.DataFrame({2173:[[-40.47, -5.41], [0., 0., 1., 2., 2., 3., 4., 5.,]],
36366:[[-40.47, -5.41], [0., 0., 1., 2., 2., 3., 4., 5.,]]})

,2173,36366
0,"[-40.47, -5.41]","[-40.47, -5.41]"
1,"[0.0, 0.0, 1.0, 2.0, 2.0, 3.0, 4.0, 5.0]","[0.0, 0.0, 1.0, 2.0, 2.0, 3.0, 4.0, 5.0]"

In [67]:
x_w_nan[:, 0]

array([ 2173., 36366.,  2174., 24012., 24019., 24030., 24037., 24078.,
       24095., 24150., 24151., 24165., 24167., 24169., 24187., 24190.,
       24206., 24233., 24235., 24265., 24313., 24315., 24330., 24455.,
       24456., 24505., 24506., 24510., 24511., 24512., 24552., 24553.,
       24554., 24555., 24556., 24557., 24558., 24559., 24578., 24579.,
       24580., 24581., 24582., 24585., 24586., 24587., 24588., 24589.,
       24590., 24591., 24592., 24598., 24601., 24620., 24629., 24633.,
       24648., 24651., 24724., 24740., 36620., 36625., 36629., 36649.,
       36658.,    61.,    70.,   146.,   532.])

In [80]:
np.reshape(pd.date_range(start='1973-01-01', end='2026-07-31', freq='D'), (-1, 1))

array([['1973-01-01T00:00:00.000000'],
       ['1973-01-02T00:00:00.000000'],
       ['1973-01-03T00:00:00.000000'],
       ...,
       ['2026-07-29T00:00:00.000000'],
       ['2026-07-30T00:00:00.000000'],
       ['2026-07-31T00:00:00.000000']],
      shape=(19570, 1), dtype='datetime64[us]')

In [72]:
help(pd.date_range)

Help on function date_range in module pandas:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize: 'bool' = False, name: 'Hashable | None' = None, inclusive: 'IntervalClosedType' = 'both', *, unit: 'TimeUnit | None' = None, **kwargs) -> 'DatetimeIndex'
    Return a fixed frequency DatetimeIndex.

    Returns the range of equally spaced time points (where the difference between any
    two adjacent points is specified by the given frequency) such that they fall in the
    range `[start, end]` , where the first one and the last one are, resp., the first
    and last time points in that range that fall on the boundary of ``freq`` (if given
    as a frequency string) or that are valid for ``freq`` (if given as a
    :class:`pandas.tseries.offsets.DateOffset`). If ``freq`` is positive, the points
    satisfy `start <[=] x <[=] end`, and if ``freq`` is negative, the points satisfy
    `end <[=] x <[=] start`. (If exactly one of ``start``, ``end``, or ``freq`` is *not*
    specified, this missing parameter can be computed given ``periods``, the number of
    timesteps in the range. See the note below.)

    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str, Timedelta, datetime.timedelta, or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5h'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive unless timezone-aware datetime-likes are passed.
    normalize : bool, default False
        Normalize start/end dates to midnight before generating date range.
    name : Hashable, default None
        Name of the resulting DatetimeIndex.
    inclusive : {"both", "neither", "left", "right"}, default "both"
        Include boundaries; Whether to set each bound as closed or open.
    unit : {'s', 'ms', 'us', 'ns', None}, default None
        Specify the desired resolution of the result.
        If not specified, this is inferred from the 'start', 'end', and 'freq'
        using the same inference as :class:`Timestamp` taking the highest
        resolution of the three that are provided.

        .. versionadded:: 2.0.0
    **kwargs
        For compatibility. Has no effect on the result.

    Returns
    -------
    DatetimeIndex
        A DatetimeIndex object of the generated dates.

    See Also
    --------
    DatetimeIndex : An immutable container for datetimes.
    timedelta_range : Return a fixed frequency TimedeltaIndex.
    period_range : Return a fixed frequency PeriodIndex.
    interval_range : Return a fixed frequency IntervalIndex.

    Notes
    -----
    Of the four parameters ``start``, ``end``, ``periods``, and ``freq``,
    a maximum of three can be specified at once. Of the three parameters
    ``start``, ``end``, and ``periods``, at least two must be specified.
    If ``freq`` is omitted, the resulting ``DatetimeIndex`` will have
    ``periods`` linearly spaced elements between ``start`` and ``end``
    (closed on both sides).

    To learn more about the frequency strings, please see
    :ref:`this link<timeseries.offset_aliases>`.

    Examples
    --------
    **Specifying the values**

    The next four examples generate the same `DatetimeIndex`, but vary
    the combination of `start`, `end` and `periods`.

    Specify `start` and `end`, with the default daily frequency.

    >>> pd.date_range(start="1/1/2018", end="1/08/2018")
    DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
                   '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
                  dtype='datetime64[us]', freq='D')

    Specify timezone-aware `start` and `end`, with the default daily frequency.

    >>> pd.date_range(
    ...     start=pd.to_datetime("1/1/2018").tz_localize("Europe/Berlin"),
    ...     end=pd.to_datetime("1/08/2018").tz_localize("Europe/Berlin"),
    ... )
    DatetimeIndex(['2018-01-01 00:00:00+01:00', '2018-01-02 00:00:00+01:00',
                   '2018-01-03 00:00:00+01:00', '2018-01-04 00:00:00+01:00',
                   '2018-01-05 00:00:00+01:00', '2018-01-06 00:00:00+01:00',
                   '2018-01-07 00:00:00+01:00', '2018-01-08 00:00:00+01:00'],
                  dtype='datetime64[us, Europe/Berlin]', freq='D')

    Specify `start` and `periods`, the number of periods (days).

    >>> pd.date_range(start="1/1/2018", periods=8)
    DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
                   '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
                  dtype='datetime64[us]', freq='D')

    Specify `end` and `periods`, the number of periods (days).

    >>> pd.date_range(end="1/1/2018", periods=8)
    DatetimeIndex(['2017-12-25', '2017-12-26', '2017-12-27', '2017-12-28',
                   '2017-12-29', '2017-12-30', '2017-12-31', '2018-01-01'],
                  dtype='datetime64[us]', freq='D')

    Specify `start`, `end`, and `periods`; the frequency is generated
    automatically (linearly spaced).

    >>> pd.date_range(start="2018-04-24", end="2018-04-27", periods=3)
    DatetimeIndex(['2018-04-24 00:00:00', '2018-04-25 12:00:00',
                   '2018-04-27 00:00:00'],
                  dtype='datetime64[us]', freq=None)

    **Other Parameters**

    Changed the `freq` (frequency) to ``'ME'`` (month end frequency).

    >>> pd.date_range(start="1/1/2018", periods=5, freq="ME")
    DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
                   '2018-05-31'],
                  dtype='datetime64[us]', freq='ME')

    Multiples are allowed

    >>> pd.date_range(start="1/1/2018", periods=5, freq="3ME")
    DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
                   '2019-01-31'],
                  dtype='datetime64[us]', freq='3ME')

    `freq` can also be specified as an Offset object.

    >>> pd.date_range(start="1/1/2018", periods=5, freq=pd.offsets.MonthEnd(3))
    DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
                   '2019-01-31'],
                  dtype='datetime64[us]', freq='3ME')

    Specify `tz` to set the timezone.

    >>> pd.date_range(start="1/1/2018", periods=5, tz="Asia/Tokyo")
    DatetimeIndex(['2018-01-01 00:00:00+09:00', '2018-01-02 00:00:00+09:00',
                   '2018-01-03 00:00:00+09:00', '2018-01-04 00:00:00+09:00',
                   '2018-01-05 00:00:00+09:00'],
                  dtype='datetime64[us, Asia/Tokyo]', freq='D')

    `inclusive` controls whether to include `start` and `end` that are on the
    boundary. The default, "both", includes boundary points on either end.

    >>> pd.date_range(start="2017-01-01", end="2017-01-04", inclusive="both")
    DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04'],
                  dtype='datetime64[us]', freq='D')

    Use ``inclusive='left'`` to exclude `end` if it falls on the boundary.

    >>> pd.date_range(start="2017-01-01", end="2017-01-04", inclusive="left")
    DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03'],
                  dtype='datetime64[us]', freq='D')

    Use ``inclusive='right'`` to exclude `start` if it falls on the boundary, and
    similarly ``inclusive='neither'`` will exclude both `start` and `end`.

    >>> pd.date_range(start="2017-01-01", end="2017-01-04", inclusive="right")
    DatetimeIndex(['2017-01-02', '2017-01-03', '2017-01-04'],
                  dtype='datetime64[us]', freq='D')

    **Specify a unit**

    >>> pd.date_range(start="2017-01-01", periods=10, freq="100YS", unit="s")
    DatetimeIndex(['2017-01-01', '2117-01-01', '2217-01-01', '2317-01-01',
                   '2417-01-01', '2517-01-01', '2617-01-01', '2717-01-01',
                   '2817-01-01', '2917-01-01'],
                  dtype='datetime64[s]', freq='100YS-JAN')

In [71]:
x_w_nan[:, 3:].T

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan,  0., nan],
       [nan, nan, nan, ..., nan,  0., nan],
       ...,
       [nan,  0.,  0., ...,  0., nan, nan],
       [nan,  0.,  0., ...,  0., nan, nan],
       [nan,  0.,  0., ...,  0., nan, nan]], shape=(19570, 69))

In [68]:
x_w_nan[:, [1, 2]]

array([[-40.4797  ,  -5.4164  ],
       [-40.9108  ,  -4.4156  ],
       [-41.1567  ,  -5.0586  ],
       [-40.941556,  -4.164583],
       [-40.678556,  -5.175361],
       [-40.748222,  -4.161083],
       [-40.312361,  -5.393778],
       [-40.766694,  -5.533   ],
       [-40.923889,  -4.744889],
       [-40.700917,  -5.719417],
       [-40.75    ,  -6.05    ],
       [-40.477639,  -5.412389],
       [-40.348639,  -5.69325 ],
       [-40.412778,  -5.14675 ],
       [-40.853167,  -5.433417],
       [-40.292222,  -5.063333],
       [-40.719389,  -5.116778],
       [-40.735833,  -4.700278],
       [-41.083333,  -4.95    ],
       [-40.533333,  -4.933333],
       [-40.761611,  -4.903861],
       [-40.70675 ,  -5.905833],
       [-40.922611,  -5.04925 ],
       [-40.909306,  -4.426944],
       [-40.703917,  -5.212   ],
       [-40.827944,  -4.750111],
       [-40.950556,  -4.136111],
       [-40.833306,  -4.283   ],
       [-41.063528,  -4.382278],
       [-40.676389,  -5.905833],
       [-40.617611,  -5.787861],
       [-40.345306,  -5.571444],
       [-40.499111,  -5.455861],
       [-40.55    ,  -5.583   ],
       [-40.483306,  -5.683   ],
       [-40.264222,  -5.300806],
       [-40.177667,  -5.201556],
       [-40.211611,  -5.484917],
       [-40.864667,  -4.176167],
       [-40.823056,  -4.176167],
       [-40.753167,  -4.213917],
       [-40.798444,  -4.444917],
       [-40.972028,  -4.557278],
       [-41.097472,  -4.795556],
       [-40.666694,  -4.7     ],
       [-40.75775 ,  -5.065583],
       [-40.1585  ,  -4.987333],
       [-40.593139,  -5.048556],
       [-40.917306,  -5.226889],
       [-40.85575 ,  -5.509361],
       [-40.63625 ,  -5.40675 ],
       [-40.711444,  -5.269139],
       [-40.542917,  -4.946639],
       [-40.43325 ,  -5.484444],
       [-40.3495  ,  -5.6745  ],
       [-40.491194,  -5.680222],
       [-40.295167,  -5.621083],
       [-40.580667,  -5.058722],
       [-40.792917,  -5.313694],
       [-40.791611,  -6.008583],
       [-40.861833,  -4.148583],
       [-40.672389,  -4.710667],
       [-40.808278,  -5.226194],
       [-40.326389,  -5.059944],
       [-40.229389,  -5.09775 ],
       [-40.481111,  -5.421111],
       [-40.874167,  -4.745556],
       [-40.66    ,  -5.16    ],
       [-40.672128,  -5.186636]])

In [65]:
x = np.loadtxt('../data/raw/pr_daily_funceme_34750000_19730101_20260731.txt')
x_w_nan = np.where(x==-999., np.nan, x)
#pd.DataFrame(x_w_nan)
#pd.DataFrame(x)

In [41]:
df = pd.read_csv('../data/raw/34750000.txt', header=None)
head_tail_info(df, 5)

<class 'pandas.DataFrame'>
RangeIndex: 8090 entries, 0 to 8089
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8090 non-null   float64
 1   1       8090 non-null   float64
dtypes: float64(2)
memory usage: 126.5 KB

              0         1
0    -40.814582 -4.626249
1    -40.813749 -4.626249
2    -40.813749 -4.627083
3    -40.814582 -4.627083
4    -40.814582 -4.627916
8085 -40.812916 -4.623749
8086 -40.813749 -4.623749
8087 -40.813749 -4.624583
8088 -40.814582 -4.624583
8089 -40.814582 -4.626249

None

In [39]:
df = pd.read_excel('../data/raw/34750000_Vazoes.xlsx', parse_dates=['Data'])
head_tail_info(df, 5)

<class 'pandas.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    694 non-null    datetime64[us]
 1   Media   691 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 11.0 KB

          Data     Media
0   1964-02-01       NaN
1   1964-03-01  279.9676
2   1964-04-01  502.0310
3   1964-05-01  213.3629
4   1964-06-01   25.9365
689 2021-08-01    0.0200
690 2021-09-01    0.0000
691 2021-10-01    0.0000
692 2021-11-01    4.4730
693 2021-12-01    1.3916

None