# *Setup*

In [1]:
%%time
import numpy as np
import pandas as pd

from hid_avan.eda import head_tail_info

CPU times: total: 1.19 s
Wall time: 1.19 s

# Montando o *dataset* `P-ETP-Q`

In [3]:
df_pr = pd.read_csv('../../data/processed/aggregated-by-mean_timeseries_monthly_avg_pr.csv', parse_dates=['date'])

df_q  = pd.read_excel('../../data/raw/34750000_Vazoes.xlsx', parse_dates=['Data'])
df_q.rename({'Data':'date', 'Media':'avg_q'}, axis='columns', inplace=True)

df_et = pd.read_csv('../../data/processed/timeseries_monthly_et.csv', parse_dates=['date'])

head_tail_info(df_pr, n=2)
head_tail_info(df_q, n=2)
head_tail_info(df_et, n=2)

<class 'pandas.DataFrame'>
RangeIndex: 643 entries, 0 to 642
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              643 non-null    datetime64[us]
 1   agg_mean__avg_pr  643 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 10.2 KB

          date  agg_mean__avg_pr
0   1973-01-01          1.483333
1   1973-02-01          4.489286
641 2026-06-01          0.303568
642 2026-07-01          0.073574

None

<class 'pandas.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    694 non-null    datetime64[us]
 1   avg_q   691 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 11.0 KB

          date     avg_q
0   1964-02-01       NaN
1   1964-03-01  279.9676
692 2021-11-01    4.4730
693 2021-12-01    1.3916

None

<class 'pandas.DataFrame'>
RangeIndex: 751 entries, 0 to 750
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    751 non-null    datetime64[us]
 1   et      751 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 11.9 KB

          date     et
0   1964-01-01  229.4
1   1964-02-01  176.0
749 2026-06-01  142.3
750 2026-07-01  162.8

None

In [4]:
df_pr_et_q_inner = df_q.set_index('date').join([df_pr.set_index('date'),
                                                df_et.set_index('date')],
                                               how='inner')
df_pr_et_q_inner.reset_index(drop=False, inplace=True)
#df_pr_et_q_inner.to_csv('../../data/processed/pr-et-q_monthly_inner-joined.csv', index=False)
head_tail_info(df_pr_et_q_inner)

<class 'pandas.DataFrame'>
RangeIndex: 587 entries, 0 to 586
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              587 non-null    datetime64[us]
 1   avg_q             585 non-null    float64
 2   agg_mean__avg_pr  587 non-null    float64
 3   et                587 non-null    float64
dtypes: datetime64[us](1), float64(3)
memory usage: 18.5 KB

          date     avg_q  agg_mean__avg_pr     et
0   1973-01-01   10.3429          1.483333  229.4
1   1973-02-01    3.0353          4.489286  176.0
2   1973-03-01   35.2784          8.745161  171.7
3   1973-04-01  141.4698          8.866667  140.9
4   1973-05-01   43.2115          4.729032  147.6
582 2021-08-01    0.0200          0.000314  191.7
583 2021-09-01    0.0000          0.031354  213.9
584 2021-10-01    0.0000          0.762727  245.3
585 2021-11-01    4.4730          1.048943  242.0
586 2021-12-01    1.3916          1.381641  250.0

None