# *Setup*

In [28]:
%%time
import numpy as np
import pandas as pd

from hid_avan.eda import head_tail_info

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(context='notebook', style='ticks')
plt.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['mathtext.fontset'] = 'cm'

CPU times: total: 0 ns
Wall time: 504 μs

# Analisando as médias históricas de cada mês

## Utilizando *dataset* `P-ETP`, sem necessariamente condizer os valores não faltantes com a série `Q`

In [115]:
df = pd.read_csv('../../data/processed/pr-et_monthly_inner-joined.csv', parse_dates=['date'])

df_only_month = pd.concat((df.iloc[:, 0].dt.month, df.iloc[:, 1:]), axis=1)
df_only_month.rename({'date' : 'month'}, axis='columns', inplace=True)
del df

head_tail_info(df_only_month, n=5)

<class 'pandas.DataFrame'>
RangeIndex: 643 entries, 0 to 642
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   month              643 non-null    int32
 1   agg_total__avg_pr  643 non-null    float64
 2   et                 643 non-null    float64
dtypes: float64(2), int32(1)
memory usage: 12.7 KB

     month  agg_total__avg_pr     et
0        1          44.500000  229.4
1        2         125.700000  176.0
2        3         271.100000  171.7
3        4         266.000000  140.9
4        5         146.600000  147.6
638      3         162.491283  171.7
639      4         130.307998  140.9
640      5          47.085833  147.6
641      6           9.107036  142.3
642      7           2.280789  162.8

None

In [117]:
df_climatology_pr_et = df_only_month.groupby(
    by='month',
    as_index=False
).agg(
    historical_avg_pr=('agg_total__avg_pr', 'mean'),
    historial_avg_et=('et', 'mean')
)

df_climatology_pr_et.month = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
df_climatology_pr_et.to_csv('../../reports/tables/climatology_pr-et.csv')
head_tail_info(df_climatology_pr_et, 6)

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   month              12 non-null     str
 1   historical_avg_pr  12 non-null     float64
 2   historial_avg_et   12 non-null     float64
dtypes: float64(2), str(1)
memory usage: 420.0 bytes

   month  historical_avg_pr  historial_avg_et
0    Jan          93.144876             229.4
1    Feb         114.054010             176.0
2    Mar         175.001615             171.7
3    Apr         140.309715             140.9
4    May          59.094903             147.6
5    Jun          17.570391             142.3
6    Jul           9.880301             162.8
7    Aug           3.091675             191.7
8    Sep           2.998394             213.9
9    Oct           4.228818             245.3
10   Nov          10.641083             242.0
11   Dec          26.603250             250.0

None